### ISSUE TITLE
lcovonly reporter not working

### ISSUE THREAD

**Issue by nfantone** [mattlewis92/karma-coverage-istanbul-reporter#11]
I'm using `karma-typescript` to compile an Angular application before running tests. Configuring a `'lcovonly'`or `'text-lcov'` reporter in the `karmaTypescriptConfig.reports` array, produces the following output:

```sh
08 04 2017 18:26:12.993:ERROR [karma]: TypeError: Cannot read property 'start' of undefined
    at node_modules/istanbul-reports/lib/lcovonly/index.js:32:42
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at Visitor.(anonymous function) [as onDetail] (node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (node_modules/istanbul-lib-report/lib/tree.js:123:17)
# ...
```

Other reporters (like `'text-summary'`) seem to work as expected.

**Comment by mattlewis92** [comment]
This is because karma-typescript [uses the 0.x version of istanbul](https://github.com/monounity/karma-typescript/blob/master/package.json#L74) and this module uses the istanbul 1.x APIs to do the reporting. The 2 APIs are not completely compatible which is why you're getting that error. karma-typescript already has baked in support for remapping coverage reports though via the remap-istanbul library so this module shouldn't be necessary when using karma-typescript. Hope that helps! 😄

**Comment by nfantone** [comment]
Ok, understood. Not entirely sure how to setup coverage reports with `karma-typescript` - but will figure it out.

Thank you so much the answer!

**Comment by mattlewis92** [comment]
I think it's documented in their readme 😀
