### ISSUE TITLE
Inconsistent runs fail to connect to Chrome

### ISSUE THREAD

**Issue by kentonbmax** [mattlewis92/karma-coverage-istanbul-reporter#24]
Having trouble getting code coverage to run consistently and could use some help. If I run this back to back I get inconsistent results. Sometimes it succeeds and fails on the very next run. Error is no message in 10000ms as if another orphaned process is running preventing connection. If I remove the coverage call and just run npm test I get success all the time. I noticed that if I have no instances of chrome running and no instances of nodejs, that after running and chrome window closes one seems to be orphaned. Is there a way to turn on better more verbose error logging to find the root cause? 

Using latest Karma and Jasmine. 
![image](https://user-images.githubusercontent.com/15804484/30556043-7e14d0a4-9c77-11e7-8bee-db3afcc23cb9.png)

Note: `ng test` works every time its ran.

**Comment by mattlewis92** [comment]
That's odd, are you able to share a minimal repo that reproduces your problem? I use this module with karma / angular / chrome as well and have never hit any issues like the one you're describing which would suggest to me it might be something else causing the problem. Are you on the latest chrome / tried `ChromeHeadless` instead of `Chrome` as the browser? In regards to logging I would just edit the raw source code in your node_modules directory. If you put a log [here](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/src/reporter.js#L31) and [here](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/src/reporter.js#L151) do they both get outputted after a failing test run?

**Comment by kentonbmax** [comment]
Update - I rolled back to Jasmine-core 2.5.2 like several posts recommended. This allowed me to run my current set of tests. After writing about 10 more for a new view I started getting the disconnect error after running about half of my test suite. I believe this is occurring because a single test is hanging. While not running code coverage works without issue, I think a nice to have would be a test timeout and continue feature. This would allow the user to configure a timeout and fail the test (identify) that has the issue but not break the rest of the suite.

**Comment by mattlewis92** [comment]
If a single test was hanging then this reporter should never trigger - it only runs after all tests have finished. It also doesn't do anything async so there is no way of adding a timeout. It sounds to me that this might be a conflict between how istanbul instruments code and jasmine running tests, but all that happens before this lib ever gets ran. If you're using the angular CLI, there are other modules at play that might be responsible for the issues you're experiencing, you might be better off raising an issue over there (with a minimal runnable repo that reproduces your issue).
