### ISSUE TITLE
JSON coverage report is broken on Windows

### ISSUE THREAD

**Issue by cexbrayat** [mattlewis92/karma-coverage-istanbul-reporter#5]
For a developper on Windows, the generated coverage report is broken as the keys are file paths.

For example:
```
{"total": {"lines":{"total":28,"covered":28,"skipped":0,"pct":100},"statements":
{"total":31,"covered":31,"skipped":0,"pct":100},"functions":
{"total":3,"covered":2,"skipped":0,"pct":66.67},"branches":
{"total":0,"covered":0,"skipped":0,"pct":100}}
,"C:\Users\ufot\Documents\angular2\ponyracer\src\polyfills.ts": {"lines":
{"total":3,"covered":3,"skipped":0,"pct":100},"functions":
{"total":0,"covered":0,"skipped":0,"pct":100},"statements":
{"total":3,"covered":3,"skipped":0,"pct":100},"branches":
{"total":0,"covered":0,"skipped":0,"pct":100}}
```

Trying to parse this report with `JSON.parse()` will fail.

**Comment by mattlewis92** [comment]
Thanks for the report! This looks like a bug with istanbul-reports itself, it looks like it was [fixed in the json reporter](https://github.com/istanbuljs/istanbul-reports/commit/4e5266e5edb0deadc75fe3eab3b7e3ef31f9af31), but not the `json-summary` reporter. Can you confirm that you're using the `json-summary` reporter and not the `json` one? If so I'll send istanbul a PR with the fix, as fixing it in this lib would result in broken behaviour when it's fixed upstream.

**Comment by cexbrayat** [comment]
I confirm that we use `json-summary` and not `json`.
Thanks for your help!

**Comment by mattlewis92** [comment]
I've sent a PR to istanbul-reports with a fix: https://github.com/istanbuljs/istanbul-reports/pull/20. As soon as it gets merged and released you'll just need to update your nested npm dependencies (either clear node_modules or if using yarn `yarn upgrade`). Hope that helps!

**Comment by cexbrayat** [comment]
Thank you very much! Sorry to have opened it here: as angular-cli shifted to `karma-coverage-istanbul-reporter` and the problem appeared at the same time, this was an obvious (but wrong) suspect :)

**Comment by mattlewis92** [comment]
No problem, this is one of the common pain points of nested dependencies 😄
