### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by fchiumeo** [mattlewis92/karma-coverage-istanbul-reporter#50]
when install npm thrown this warn
```shell
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
```

**Comment by mattlewis92** [comment]
`istanbul-lib-hook` is not a [direct dependency](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/package.json#L40-L42) of this package, I'm guessing it's because `istanbul-lib-hook` is being cached somewhere locally for you, if you do `npm update --depth 2` it will probably fix it.

**Comment by fchiumeo** [comment]
it's a [transitive dependency](https://github.com/istanbuljs/istanbuljs/blob/c13d273a721e396fb746cf4cb745e6d32f5c511c/packages/istanbul-api/package.json#L42) of istanbul-api
``
npm update --depth 2
`` not working in this case

**Comment by mattlewis92** [comment]
Try doing:
```
rm -rf node_modules package-lock.json
npm install
```

**Comment by fchiumeo** [comment]
istanbul-api 1.3.1 is the latest version, 2.0.5 marked as next
